---
title: "NavyBlue"
author: "Cheang Ming, Nasruddine, Walter, Calvert, Chrystal"
format: html
editor: visual
---

## Import packages

```{r}
#| label: Load all libraries
#| message: FALSE
library(tidyverse)
library(ggplot2)
library(dplyr)
```

## Import Data

```{r}
#| label: Load all datasets

mot2000 <- read.csv("mode_of_transport_2000.csv", skip = 11, nrow = 15)
mot2005 <- read.csv("mode_of_transport_2005.csv", skip = 11, nrow = 15)
mot2010 <- read.csv("mode_of_transport_2010.csv", skip = 11, nrow = 13)
mot2015 <- read.csv("mode_of_transport_2015.csv", skip = 11, nrow = 12)
mot2020 <- read.csv("mode_of_transport_2020.csv", skip = 11, nrow = 13)
colnames(mot2000) <- trimws(colnames(mot2000))
colnames(mot2005) <- trimws(colnames(mot2005))
colnames(mot2010) <- trimws(colnames(mot2010))
colnames(mot2015) <- trimws(colnames(mot2015))
colnames(mot2020) <- trimws(colnames(mot2020))
# Trim whitespace from all character columns
mot2000 <- mot2000 |> mutate(across(where(is.character), trimws))
mot2005 <- mot2005 |> mutate(across(where(is.character), trimws))
mot2010 <- mot2010 |> mutate(across(where(is.character), trimws))
mot2015 <- mot2015 |> mutate(across(where(is.character), trimws))
mot2020 <- mot2020 |> mutate(across(where(is.character), trimws))
```

## Adjust 2020 dataset use row 1 as header

```{r}
#| label: Adjust 2020 dataset


# Replace column names that start with 'X' followed by digits with values from the first row
new_names <- ifelse(grepl("^X\\.\\d+$", names(mot2020)), mot2020[1, which(grepl("^X\\.\\d+$", names(mot2020)))], names(mot2020))

# Set the new column names
names(mot2020) <- new_names

# Remove the first row used as headers
mot2020 <- mot2020[-1, ]

# Rename the "X" column to "categories"
colnames(mot2000)[which(names(mot2000) == "X")] <- "Categories"
colnames(mot2005)[which(names(mot2005) == "X")] <- "Categories"
colnames(mot2010)[which(names(mot2010) == "X")] <- "Categories"
colnames(mot2015)[which(names(mot2015) == "X")] <- "Categories"
colnames(mot2020)[which(names(mot2020) == "X")] <- "Categories"

# Reset row names
row.names(mot2020) <- NULL
```

## Print Table

```{r}
#| label: Print all datasets
#| message: FALSE

mot2000
mot2005
mot2010
mot2015
mot2020
```

# Select the first column and the Total

```{r}
#| label: Select the first column and the Total
#| message: FALSE

mot2000 <- mot2000 |> select(1, 2)
mot2005 <- mot2005 |> select(1, 2)
mot2010 <- mot2010 |> select(1, 2)
mot2015 <- mot2015 |> select(1, 2)
mot2020 <- mot2020 |> select(1, 2) #|> mutate(Categories = recode(Categories, "Taxi/Private Hire Car Only" = "Taxi Only"))

mot2000
mot2005
mot2010
mot2020
```

# Join all datasets (Rename Total to the year)

```{r}
#| label: Join all datasets
#| message: FALSE

mot <- full_join(mot2000, mot2005, by = "Categories") |>
  full_join(mot2010, by = "Categories") |>
  full_join(mot2015, by = "Categories") |>
  full_join(mot2020, by = "Categories") |>
  rename(`2000` = Total.x, `2005` = Total.y, `2010` = Total.x.x, `2015` = Total.y.y, `2020` = Total)

mot
```
